#!/bin/bash

set -e
set -x

rm -f cookies
curl --cookie-jar cookies -X POST https://pub-submit-stg.escholarship.org/dspace-rest/login -d "email=martin.haye%40ucop.edu&password=Say4lank-viscus"
# Embargoed:
#curl --cookie cookies https://pub-submit-stg.escholarship.org/dspace-rest/bitstreams/qttt8s1x7d/content/qttt8s1x7d.pdf/policy
# Published:
curl --cookie cookies https://pub-submit-stg.escholarship.org/dspace-rest/bitstreams/qt52d8w10g/content/qt52d8w10g.pdf/policy
# Withdrawn:
#curl --cookie cookies https://pub-submit-stg.escholarship.org/dspace-rest/bitstreams/qt19m509w8/content/qt19m509w8.pdf/policy
